---
title: "Integrative Simulation Exercises"
author: Kris Sankaran
output: rmdformats::readthedown
---

```{r}
suppressPackageStartupMessages({
  library(MIGsim)
  library(SummarizedExperiment)
  library(gamboostLSS)
  library(glue)
  library(mixOmics)
  library(ggplot2)
  library(scDesigner)
})
set.seed(20240611)
```

### Vertical Integration

```{r}
data(icu)
simulator <- list()
for (i in seq_along(icu)) {
  simulator[[i]] <- setup_simulator(icu[[i]], ~ Category, ~ GaussianLSS()) |>
    estimate(nu = 0.05)
}

names(simulator) <- names(icu)
```

evaluate similarity between real and simulated.

```{r}
library(purrr)
library(dplyr)
icu_sim <- map(simulator, sample)

i <- 3
ix <- order(rowSums(assay(icu[[i]])), decreasing = TRUE)
abundant <- rownames(icu[[i]])[ix]

merged_data <- bind_rows(
    template = pivot_experiment(icu[[i]]),
    simulated = pivot_experiment(icu_sim[[i]]),
    .id = "source"
) |>
filter(feature %in% head(abundant, 20))

ggplot(merged_data) +
  geom_vline(xintercept = 0) +
  geom_boxplot(aes(value, reorder(feature, value), fill = source)) +
  facet_grid(. ~ reorder(Category, -value))
```

Experiment with CCA Nulls

```{r}
merged <- join_copula(simulator[c(1, 3)], copula_adaptive(thr = 0.01))
heatmap(copula_parameters(merged))
```

```{r}
xy <- sample(merged) |>
  assay() |>
  t()
ix <- map(icu, rownames)
cca_result <- mixOmics::rcc(xy[, ix[[1]]], xy[, ix[[3]]], method = "shrinkage")
```

```{r}
rho_null <- copula_parameters(merged)
dimnames(rho_null) <- list(colnames(xy), colnames(xy))
rho_null[ix[[1]], ix[[3]]] <- 0
rho_null[ix[[3]], ix[[1]]] <- 0

B <- 100
cancors <- list()
for (b in seq_len(B)) {
  xy_null <- merged |>
    mutate_correlation(rho_null) |>
    sample() |>
    assay() |>
    t()

  cancors[[glue("sim_{b}")]] <- mixOmics::rcc(xy_null[, ix[[1]]], xy_null[, ix[[3]]], method = "shrinkage")$cor
}
```

```{r}
cancors[["true"]] <- cca_result$cor

bind_rows(cancors, .id = "rep") |>
  tidyr::pivot_longer(-rep, names_to = "loading") |>
  mutate(
    source = stringr::str_detect(rep, "true"),
    loading = as.integer(loading)
  ) |>
  ggplot() +
    geom_boxplot(aes(factor(loading), value, fill = source, col = source), alpha = 0.6)
```

Next, an example where we either do or do not have any true association with
category, to see how the integration outputs change.

```{r}
x <- map(icu, ~ t(assay(.)))
y <- colData(icu[[1]])$Category
fit <- block.splsda(x, y)
plotIndiv(fit)
```

```{r}
null_simulator <- simulator
null_simulator[[1]] <- simulator[[1]] |>
  scDesigner::mutate(1:180, link = ~ 1, family = ~ GaussianLSS()) |>
  estimate(nu = 0.05)

null_simulator[[2]] <- simulator[[2]] |>
  scDesigner::mutate(1:18, link = ~ 1, family = ~ GaussianLSS()) |>
  estimate(nu = 0.05)
```

```{r}
x <- map(null_simulator, ~ t(assay(sample(.))))
rownames(x[[1]]) <- colnames(icu[[1]])
rownames(x[[2]]) <- colnames(icu[[2]])
rownames(x[[3]]) <- colnames(icu[[3]])

y <- colData(icu[[1]])$Category
fit <- block.splsda(x, y)
plotIndiv(fit)
```

### Horizontal Integration

```{r}
load(url("https://github.com/EvaYiwenWang/Managing_batch_effects/raw/master/Managing_batch_effects/datasets/microbiome_datasets.RData"))
ad.index.keep <- which(colSums(ad.count)*100/(sum(colSums(ad.count))) > 0.01)
ad.count.keep <- ad.count[, ad.index.keep]
ad.count.keep <- ad.count.keep + 1
ad.clr <- logratio.transfo(ad.count.keep, logratio = 'CLR')
class(ad.clr) <- 'matrix' 

alzheimers <- SummarizedExperiment(
  colData = DataFrame(batch = ad.batch, treatment = ad.trt),
  assays = SimpleList(clr = t(ad.clr))
)

library(compositions)

simulator <- setup_simulator(
  alzheimers,
  ~ batch + treatment,
  ~ GaussianLSS(),
  copula = copula_adaptive(thr = .1)
) |>
  estimate(nu = 0.05, mstop = 100)

alzheimers_sim <- sample(simulator)

library(dplyr)
merged_data <- bind_rows(
    template = pivot_experiment(alzheimers),
    simulated = pivot_experiment(alzheimers_sim),
    .id = "source"
) |>
filter(feature %in% rownames(alzheimers)[1:30])

ggplot(merged_data) +
  geom_vline(xintercept = 0) +
  geom_boxplot(aes(value, reorder(feature, value), fill = source)) +
  facet_grid(. ~ reorder(treatment, -value))
```

```{r}
pca_res <- pca(t(assay(alzheimers_sim)))
pca_res <- pca(t(assay(alzheimers)))

bind_cols(pca_res$variates$X, as_tibble(colData(alzheimers))) |>
  ggplot() +
  geom_hline(yintercept = 0, linewidth = 0.8) +
  geom_vline(xintercept = 0, linewidth = 0.8) +
  geom_point(aes(PC1, PC2, col = treatment), size = 2) +
  facet_wrap(~ batch)
```
