---
title: "Joint Simulation Exercises"
author: Kris Sankaran
output: rmdformats::readthedown
---

```{r, include = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
suppressPackageStartupMessages({
  library(MIGsim)
  library(SummarizedExperiment)
  library(gamboostLSS)
  library(glue)
  library(mixOmics)
  library(ggplot2)
  library(scDesigner)
})
set.seed(202406)
theme_set(theme_classic())
```

### Interpreting PLS-DA

```{r}
data(t1d)
result <- splsda_fit(t1d)
plotIndiv(result$fit)
plotLoadings(result$fit)
```

### Simualtor Estimation

```{r}
data(t1d_order)
simulator <- setup_simulator(t1d, link_formula = ~outcome2, family = ~ GaussianLSS()) |>
  estimate(mstop = 100)

sim_exper <- sample(simulator)
sim_exper
```

### Simulator Evaluation

```{r}
correlation_hist(t1d, sim_exper)
```

```{r}
simulator <- setup_simulator(
  t1d,
  link_formula = ~outcome2,
  family = ~ GaussianLSS(),
  copula_def = copula_adaptive()
) |>
  estimate(mstop = 100)

sim_exper <- sample(simulator)
correlation_hist(t1d, sim_exper)
```


### PLS-DA Power Analysis

```{r, power-analysis-params}
config <- expand.grid(
  sample_size = floor(seq(15, 150, length.out = 5)),
  n_rep = 1:3,
  n_null = floor(seq(317, 417, length.out = 4)),
  metrics = NA
)
```

```{r power-analysis-loop}
for (i in seq_len(nrow(config))) {
  if (i == 1 || config$n_null[i] != config$n_null[i - 1]) {
    simulator <- simulator |>
      mutate(dplyr::any_of(rev(t1d_order)[1:config$n_null[i]]), link = ~1) |>
      estimate(mstop = 100)
  }

  config$metrics[i] <- (sample_n(simulator, config$sample_size[i]) |>
    splsda_fit())[["auc"]]
  print(glue("run {i}/{nrow(config)}"))
}
```

```{r}
ggplot(config, aes(sample_size, metrics, col = factor(n_null))) +
  geom_point() +
  facet_wrap(~ n_null)
```
